### ISSUE TITLE
Inconsistent add_api_route types

### ISSUE THREAD

**Issue by Kludex** [fastapi/fastapi#10236]
### Discussed in https://github.com/tiangolo/fastapi/discussions/10235

<div type='discussions-op-text'>

<sup>Originally posted by **sidekick-eimantas** September 12, 2023</sup>
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
### Direct mounting of routes
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)

app = FastAPI()
hello_handler = Hello(name="test")
app.add_api_route("/hello", hello_handler.handle, methods=["POST"])






### Mounting of paths via Router
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)


class RootRouter:
    def __init__(self, name: str):
        self.router = APIRouter()
        hello_handler = Hello(name=name)
        self.router.add_api_route("/hello", hello_handler.handle, methods=["POST"])


app = FastAPI()
root_router = RootRouter(name="test")
app.include_router(root_router.router)
```

### Description

First example produces a mypy error:
```
error: Argument 2 to "add_api_route" of "FastAPI" has incompatible type "Callable[[HelloRequest], Coroutine[Any, Any, HelloResponse]]"; expected "Callable[..., Coroutine[Any, Any, Response]]"  [arg-type]
```

Second example does not.

The types of `endpoint` parameter in `FastAPI.add_api_route` and `APIRouter.add_api_route` are inconsistent.

### Operating System

macOS

### FastAPI Version

0.103.1

### Pydantic Version

2.3.0

### Python Version

3.10.7

### Additional Context

_No response_</div>

**Comment by Kludex** [comment]
This is a valid issue. The type hint of both `endpoint` parameters should match.

Should be easy to fix - I don't know which one @tiangolo wants.

**Comment by annis-souames** [comment]
Hey @Kludex 

I want to help on this issue if no one is interested, I have used FastAPI before in some hobby projects but this is my first  OSS contribution!

**Comment by ordinary-jamie** [comment]
I'll take this if no one else is!

> I don't know which one tiangolo wants.

I would think `Callable[..., Any]` is preferred:

- `FastAPI.add_api_route` makes a direct call to `APIRouter.add_api_route` anyways 
- `fastapi.dependencies.utils.get_typed_return_annotation` has signature `def get_typed_return_annotation(call: Callable[..., Any]) -> Any:`
- A lot of other functions with similar parameters use the same typing (e.g. `FastAPI.add_api_websocket_route`)

Happy to work with either

**Comment by Alshymy22** [comment]
### Direct mounting of routes
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)

app = FastAPI()
hello_handler = Hello(name="test")
app.add_api_route("/hello", hello_handler.handle, methods=["POST"])






### Mounting of paths via Router
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)


class RootRouter:
    def __init__(self, name: str):
        self.router = APIRouter()
        hello_handler = Hello(name=name)
        self.router.add_api_route("/hello", hello_handler.handle, methods=["POST"])


app = FastAPI()
root_router = RootRouter(name="test")
app.include_router(root_router.router

**Comment by eydenbarboza** [comment]
hi @Kludex Is this still a valid issue? I want to help on this issue if no one is interested

**Comment by devkan** [comment]
Hi.. is closed? I like FastAPI and want to contribute..

**Comment by eydenbarboza** [comment]
Hi, this issue is closed ?

**Comment by tiangolo** [comment]
Thanks all! This was handled in https://github.com/fastapi/fastapi/pull/10240 :rocket:
