### ISSUE TITLE
Using fast API's multi-value Query parameters, but only receiving the last value

### ISSUE THREAD

**Issue by syxiao2018** [fastapi/fastapi#11993]
I followed the method in the document (https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values-with-defaults)and the parameters of the interface list, but the data obtained is always only the last data. 
like this:
localhost:8000/path/getList?q=Value1&q=Value2

@router.get("/path/getList")
async def get_list(
        command: Union[list[str], None] = Query(default=None)
):
    for item in command:
        print(item)

console only log one data: Value2, Is there any way to troubleshoot?

**Comment by Kludex** [comment]
Please create a discussion.
