### ISSUE TITLE
Some Bugs Regarding File Upload Functionality in FastAPI and Testing with Swagger UI

### ISSUE THREAD

**Issue by ShengWei42** [fastapi/fastapi#12198]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

from fastapi import FastAPI, UploadFile, File, Form
from typing import List, Optional

app = FastAPI()

@app.post("/upload/")
async def upload_files(
    required_files: List[UploadFile] = File(...), 
    optional_files: List[Optional[UploadFile]] = File(None),  
    string_list: List[str] = Form(...) 
):
    return 

This code is an example, but I combined it with Swagger UI and found multiple problems, The following questions are respectively.
1. When the file list is defined as optional, if no optional files are selected in the Swagger UI, the backend code will report an error 422, indicating that the passed parameters cannot be received.
2. form-data type data cannot be passed together with the file type, and the back-end code cannot accept both types of data at the same time.
3. File type cannot be verified in pydantic model, but this does not seem to be a bug.
4. When receiving string types, adding multiple strings in Swagger UI, in the back-end code, using List[str] to receive will treat all strings as a larger string, resulting in only one string in the List. a string.

**Comment by ShengWei42** [comment]
I hope you can consider the questions I raised carefully, which can help more people.

**Comment by Harut8** [comment]
curl -X 'POST' \
  'http://0.0.0.0:8000/walle/api/v1/ai-knowledge/document-content' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer token' \
  -H 'Content-Type: multipart/form-data' \
  -F 'groupName=string' \
  -F 'documents=@file.txt;type=text/plain'
  
   @ai_document_router.post("/document-content")
    @inject
    async def upload_document_content(
        self,
        background_tasks: BackgroundTasks,
        group_name: str = Form(  # issue with pydantic
            ...,
            description="Group name",
            alias="groupName",
            validation_alias="groupName",
        ),
        documents: list[UploadFile] = File(...),
        organization_id: int = Depends(get_user_organization),
        ai_document_service: AiDocumentService = Depends(
            Provide[DependencyContainer.ai_document_service]
        ),
    ):
    
    {
  "detail": {
    "message": "('body', 'groupName'): Field required",
    "code": "VALIDATION_ERROR"
  }
}

**Comment by Harut8** [comment]
It has been working untill last update (

**Comment by ShengWei42** [comment]
I have received your reply, which means that in the latest version, these issues are really some bugs?

**Comment by ShengWei42** [comment]
I discovered these problems while working on a complex interface for file uploading in my company, which has been bothering me for a long time, and I have yet to find other developers in issue who have raised similar issues.Thanks for your reply.

**Comment by TBBTOM** [comment]
@ShengWei42 ,I have encountered a similar issue. Regarding the 422 error you mentioned, I used your code to create an endpoint. When making a request directly through Swagger, it results in a 422 error. However, when using an API testing tool (I used Apifox) to request this endpoint, it is successful. I did not encounter the issue where multiple strings become one long string. It seems like a frontend Swagger parsing issue. I have also experienced 422 errors with similar endpoints, but there are no issues when not using Swagger. I hope the official team can address this problem when they have time,think.
![image](https://github.com/user-attachments/assets/3c5d6353-916f-49de-be2a-6bff40c7312f)
![image](https://github.com/user-attachments/assets/79082153-c7dc-4694-9f70-48a5c39e16d7)

![image](https://github.com/user-attachments/assets/4baa847e-5bc6-421e-b39e-63516cfc0838)

**Comment by NathanAP** [comment]
I'm not sure this is about the `0.113.0` (and `0.114.0`) changes, but trying this:

```python

from fastapi import APIRouter, Form
from pydantic import BaseModel
from typing import Annotated

class RequestBody(BaseModel):
    """
    Represents the body of this route.
    """

    path: str

@router.post("/blabla/")
async def local_searcher(body: RequestBody):
   ...
```

this leads me to `422` error everytime (through postman, starlette request, etc), so I tried to intercept this error doing: 

```python

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
   print(await request.body())
   print(exc)
```

and it printed something like: 
```
...
b"/some/path"
* BaseModel missing error (pointing to my path attribute) *
...
```

I'm not sure what I'm doing wrong.

**Comment by ShengWei42** [comment]
> I'm not sure this is about the `0.113.0` (and `0.114.0`) changes, but trying this:
>
> ```python
> from fastapi import APIRouter, Form
> from pydantic import BaseModel
> from typing import Annotated
>
> class RequestBody(BaseModel):
>     """
>     Represents the body of this route.
>     """
>
>     path: str
>
> @router.post("/blabla/")
> async def local_searcher(body: RequestBody):
>    ...
> ```
>
> leads me to `422` error everytime (through postman, starlette request, etc), so I tried to intercept this error doing:
>
> ```python
> @app.exception_handler(RequestValidationError)
> async def validation_exception_handler(request: Request, exc: RequestValidationError):
>    print(await request.body())
>    print(exc)
> ```
>
> and it printed something like:
>
> ```
> ...
> b'{ "path": "/some/path" }'
> * BaseModel missing error (pointing to my path attribute) *
> ...
> ```
>
> I'm not sure what I'm doing wrong.

I have tried many times, and I am sure that this is a bug in FastAPI itself, not a problem with our code or environment. Not only that, the Swagger UI test that comes with the framework also has many bugs, as I said above

**Comment by ShengWei42** [comment]
> @ShengWei42 ,I have encountered a similar issue. Regarding the 422 error you mentioned, I used your code to create an endpoint. When making a request directly through Swagger, it results in a 422 error. However, when using an API testing tool (I used Apifox) to request this endpoint, it is successful. I did not encounter the issue where multiple strings become one long string. It seems like a frontend Swagger parsing issue. I have also experienced 422 errors with similar endpoints, but there are no issues when not using Swagger. I hope the official team can address this problem when they have time,think.，我也遇到过类似的问题。关于您提到的422错误，我使用您的代码创建了端点。直接通过Swagger发出请求时，会导致422错误。但是，当使用API​​测试工具（我使用Apifox）请求此端点时，它是成功的。我没有遇到多个字符串变成一个长字符串的问题。这似乎是前端 Swagger 解析问题。我也遇到过类似端点的 422 错误，但不使用 Swagger 时没有问题。希望官方团队有空的时候能够解决一下这个问题，思考一下。 ![image](https://private-user-images.githubusercontent.com/44862761/367499377-3c5d6353-916f-49de-be2a-6bff40c7312f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODM3ODcsIm5iZiI6MTcyNjU4MzQ4NywicGF0aCI6Ii80NDg2Mjc2MS8zNjc0OTkzNzctM2M1ZDYzNTMtOTE2Zi00OWRlLWJlMmEtNmJmZjQwYzczMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MzEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OGRmZmFmYzc3NmFhYWQ2Zjg4NjM3MjA4MDBlZjUwYzBiZGM1ZjYwY2Q5Yjc5YTVhNzMyMWJkNzA0MzlkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9y2rSz36OxGYOtcrKZO04s87ri9qURwpKtSRJEPQq80) ![image](https://private-user-images.githubusercontent.com/44862761/367499502-79082153-c7dc-4694-9f70-48a5c39e16d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODM3ODcsIm5iZiI6MTcyNjU4MzQ4NywicGF0aCI6Ii80NDg2Mjc2MS8zNjc0OTk1MDItNzkwODIxNTMtYzdkYy00Njk0LTlmNzAtNDhhNWMzOWUxNmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MzEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNGQ1ZjI2NjJhZTJmMzFiMWJkZTRmNWY5MDMwMTBjZTE4OWFjMjA0YzNiMTJjMTU3OGEwMDY1YzM3NTMzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CADwty35UoHtB6YhFJc8cWHCQNMpLbm9KijxiO2enew)
> 
> ![image](https://private-user-images.githubusercontent.com/44862761/367499412-4baa847e-5bc6-421e-b39e-63516cfc0838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODM3ODcsIm5iZiI6MTcyNjU4MzQ4NywicGF0aCI6Ii80NDg2Mjc2MS8zNjc0OTk0MTItNGJhYTg0N2UtNWJjNi00MjFlLWIzOWUtNjM1MTZjZmMwODM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MzEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZGZmMWM0NmYwMGJhMTMwMjk4ZWVhODc3OTJiMTNkZWFiZmMzMjdhY2NmYzMwZWFmMDFlM2YxNzYyOTA2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9ifZogljB7YRFYLqVS5n-H3rdavJDQyxX9SZndantM)

There is indeed no problem in using professional testing tools, such as postman, or direct joint debugging of the front and back ends. However, there are indeed many problems with using the Swagger UI that comes with the FastAPI framework for testing. As I said above, this is at the beginning Wasted a lot of my time

**Comment by tiangolo** [comment]
Hey there, although you checked that box, it seems you're not @tiangolo, and I didn't ask you to create this issue. :sweat_smile: 

So, please open a GitHub Discussion following all the template step by step. That will allow me or others to properly help you. :coffee: 

Given that, I'm gonna close this one.
