### ISSUE TITLE
Chrome does not display Swagger UI

### ISSUE THREAD

**Issue by soevai** [fastapi/fastapi#12290]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

![image](https://github.com/user-attachments/assets/0a5523b2-3727-4e33-8590-e13b5a7c7126)

Chrome does not display Swagger UI, but Edge can. 
Is this a bug?

**Comment by ross-spencer** [comment]
@soevai you marked this as completed, but did you find a resolution, or did it resolve itself? I have been asked to look at an endpoint today and I am seeing it error on Chrome but not Firefox.
