### ISSUE TITLE
Upcoming Pydantic 2.10 is going to break version comparison checks

### ISSUE THREAD

**Issue by Viicos** [fastapi/fastapi#12901]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

The following check:

https://github.com/fastapi/fastapi/blob/5a48c37056397e47ab164ba4430807aa6fc9a710/fastapi/params.py#L108-L109

is going to be flawed when we release Pydantic 2.10 (in a week):

```python
"2.10.0" > "2.7.0"
#> False
```

**Comment by tiangolo** [comment]
Thanks for the report @Viicos! I handled it in https://github.com/fastapi/fastapi/pull/12914, it will be released in the next hours. :nerd_face:
